services:
  redis-auction:
    image: redis:6.2-alpine
    container_name: redis-auction
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    env_file:
      - ./auction-service/.env.local

  redis-gateway-registry:
    image: redis:6.2-alpine
    container_name: redis-gateway-registry
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis-data-registry:/data
    env_file:
      - ./api-gateway/.env.local

  postgres-auction:
    image: postgres:17.0
    container_name: db-auction
    env_file:
      - ./auction-service/.env.local
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres

  postgres-bidder:
    image: postgres:17.0
    container_name: db-bidder
    env_file:
      - ./bidder-service/.env.local
    ports:
      - "5433:5432"
    volumes:
      - /data/postgres:/data/postgres

  pgadmin:
    image: dpage/pgadmin4:8.12
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env

  auction-service-1:
    container_name: auction-service-1
    restart: always
    env_file:
      - ./auction-service/.env.local
    environment:
      - APP_PORT=3000
    ports:
      - "3000:3000"
    build:
      context: ./auction-service
      target: run

  auction-service-2:
    container_name: auction-service-2
    restart: always
    env_file:
      - ./auction-service/.env.local
    environment:
      - APP_PORT=3001
    ports:
      - "3001:3001"
    build:
      context: ./auction-service
      target: run

  auction-service-3:
    container_name: auction-service-3
    restart: always
    env_file:
      - ./auction-service/.env.local
    environment:
      - APP_PORT=3002
    ports:
      - "3002:3002"
    build:
      context: ./auction-service
      target: run

  bidder-service-1:
    container_name: bidder-service-1
    restart: always
    env_file:
      - ./bidder-service/.env.local
    environment:
      - APP_PORT=7000
    ports:
      - "7000:7000"
    build:
      context: ./bidder-service
      target: run

  bidder-service-2:
    container_name: bidder-service-2
    restart: always
    env_file:
      - ./bidder-service/.env.local
    environment:
      - APP_PORT=7001
    ports:
      - "7001:7001"
    build:
      context: ./bidder-service
      target: run

  bidder-service-3:
    container_name: bidder-service-3
    restart: always
    env_file:
      - ./bidder-service/.env.local
    environment:
      - APP_PORT=7002
    ports:
      - "7002:7002"
    build:
      context: ./bidder-service
      target: run

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
    env_file:
      - ./api-gateway/.env.local
    ports:
      - "5000:5000"

  service-discovery:
    container_name: service-discovery
    build:
      context: ./service-discovery
    env_file:
      - ./service-discovery/.env.local
    ports:
      - "5001:5001"

  nats:
    image: nats:latest
    container_name: nats-server
    ports:
      - "4222:4222" # NATS Client Port
      - "8222:8222" # NATS Monitoring Port
    environment:
      - NATS_CLUSTER_ADVERTISE=localhost

volumes:
  redis-data:
  redis-data-registry:
