services:
  redis:
    image: redis:6.2-alpine
    container_name: redis
    env_file:
      - ./auction-service/.env
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  redis-registry:
    image: redis:6.2-alpine
    container_name: redis-registry
    env_file:
      - ./api-gateway/.env
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis-data-registry:/data

  nats:
    image: nats:latest
    container_name: nats-server
    ports:
      - "4222:4222"
      - "8222:8222"
    environment:
      - NATS_CLUSTER_ADVERTISE=localhost

  postgres-auction:
    image: postgres:17.0
    container_name: db-auction
    env_file:
      - ./auction-service/.env
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres

  postgres-bidder:
    image: postgres:17.0
    container_name: db-bidder
    env_file:
      - ./bidder-service/.env
    ports:
      - "5433:5432"
    volumes:
      - /data/postgres:/data/postgres

  pgadmin:
    image: dpage/pgadmin4:8.12
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9095:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "4001:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  redis-data:
  redis-data-registry:
  grafana-data:
