services:
  redis-auction:
    image: redis:6.2-alpine
    container_name: redis-auction
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    env_file:
      - ./auction-service/.env.local

  redis-gateway-registry:
    image: redis:6.2-alpine
    container_name: redis-gateway-registry
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis-data-registry:/data
    env_file:
      - ./api-gateway/.env.local

  postgres-auction:
    image: postgres:17.0
    container_name: db-auction
    env_file:
      - ./auction-service/.env.local
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres

  postgres-bidder:
    image: postgres:17.0
    container_name: db-bidder
    env_file:
      - ./bidder-service/.env.local
    ports:
      - "5433:5432"
    volumes:
      - /data/postgres:/data/postgres

  pgadmin:
    image: dpage/pgadmin4:8.12
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env

  auction-service-1:
    container_name: auction-service-1
    image: tum-pad-auction-service
    restart: always
    env_file:
      - ./auction-service/.env.local
    environment:
      - APP_PORT=3000
    depends_on:
      service-discovery:
        condition: service_started
    ports:
      - "3000:3000"

  auction-service-2:
    container_name: auction-service-2
    image: tum-pad-auction-service
    restart: always
    env_file:
      - ./auction-service/.env.local
    environment:
      - APP_PORT=3001
    depends_on:
      service-discovery:
        condition: service_started
    ports:
      - "3001:3001"

  auction-service-3:
    container_name: auction-service-3
    image: tum-pad-auction-service
    restart: always
    env_file:
      - ./auction-service/.env.local
    environment:
      - APP_PORT=3002
    depends_on:
      service-discovery:
        condition: service_started
    ports:
      - "3002:3002"

  bidder-service-1:
    container_name: bidder-service-1
    image: tum-pad-bidder-service
    restart: always
    env_file:
      - ./bidder-service/.env.local
    environment:
      - APP_PORT=7000
    depends_on:
      service-discovery:
        condition: service_started
    ports:
      - "7000:7000"

  bidder-service-2:
    container_name: bidder-service-2
    image: tum-pad-bidder-service
    restart: always
    env_file:
      - ./bidder-service/.env.local
    environment:
      - APP_PORT=7001
    depends_on:
      service-discovery:
        condition: service_started
    ports:
      - "7001:7001"

  bidder-service-3:
    container_name: bidder-service-3
    image: tum-pad-bidder-service
    restart: always
    env_file:
      - ./bidder-service/.env.local
    environment:
      - APP_PORT=7002
    depends_on:
      service-discovery:
        condition: service_started
    ports:
      - "7002:7002"

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
    env_file:
      - ./api-gateway/.env.local
    depends_on:
      service-discovery:
        condition: service_started
    ports:
      - "5000:5000"

  service-discovery:
    container_name: service-discovery
    build:
      context: ./service-discovery
    env_file:
      - ./service-discovery/.env.local
    ports:
      - "5001:5001"

  nats:
    image: nats:latest
    container_name: nats-server
    ports:
      - "4222:4222"
      - "8222:8222"
    environment:
      - NATS_CLUSTER_ADVERTISE=localhost

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9095:9090"
    volumes:
      - ./prometheus.prod.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "4001:3000"
    volumes:
      - grafana-data:/var/lib/grafana

  mongo1:
    image: mongo:7.0
    container_name: mongo-1
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017',priority:3},{_id:1,host:'host.docker.internal:27018',priority:1},{_id:2,host:'host.docker.internal:27019',priority:2}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - "mongo1_data:/data/db"
      - "mongo1_config:/data/configdb"

  mongo2:
    image: mongo:7.0
    container_name: mongo-2
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27018"]
    ports:
      - 27018:27018
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "mongo2_data:/data/db"
      - "mongo2_config:/data/configdb"

  mongo3:
    image: mongo:7.0
    container_name: mongo-3
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27019"]
    ports:
      - 27019:27019
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "mongo3_data:/data/db"
      - "mongo3_config:/data/configdb"

volumes:
  redis-data:
  redis-data-registry:
  grafana-data:
  mongo1_data:
  mongo2_data:
  mongo3_data:
  mongo1_config:
  mongo2_config:
  mongo3_config:
