global:
  scrape_interval: 15s

scrape_configs:
  - job_name: tum-pad
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets:
          [
            "auction-service-1:3000",
            "auction-service-2:3001",
            "auction-service-3:3002",
            "bidder-service-1:7000",
            "bidder-service-2:7001",
            "bidder-service-3:7002",
          ]
