global:
  scrape_interval: 15s

scrape_configs:
  - job_name: tum-pad
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets:
          [
            "host.docker.internal:3000",
            "host.docker.internal:3001",
            "host.docker.internal:3002",
          ]
