# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/service_registry.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cproto/service_registry.proto\x12\x10service_registry\">\n\x0bServiceInfo\x12\x13\n\x0bserviceName\x18\x01 \x01(\t\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"4\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2`\n\x0fServiceRegistry\x12M\n\x08Register\x12\x1d.service_registry.ServiceInfo\x1a\".service_registry.RegisterResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.service_registry_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SERVICEINFO']._serialized_start=50
  _globals['_SERVICEINFO']._serialized_end=112
  _globals['_REGISTERRESPONSE']._serialized_start=114
  _globals['_REGISTERRESPONSE']._serialized_end=166
  _globals['_SERVICEREGISTRY']._serialized_start=168
  _globals['_SERVICEREGISTRY']._serialized_end=264
# @@protoc_insertion_point(module_scope)
